# Generated by Django 4.1 on 2022-09-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhostingapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccounts',
            name='username',
            field=models.CharField(max_length=15),
        ),
    ]
