# Generated by Django 4.1 on 2022-09-07 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webhostingapp', '0002_alter_useraccounts_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='resetPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('verify_code', models.CharField(max_length=100, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webhostingapp.useraccounts')),
            ],
        ),
        migrations.CreateModel(
            name='mysqlUserDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_host', models.CharField(default='mysql.st-site.tk', max_length=70)),
                ('db_port', models.IntegerField(default=3306)),
                ('db_name', models.CharField(max_length=50)),
                ('db_username', models.CharField(max_length=15)),
                ('db_password', models.CharField(max_length=256)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webhostingapp.useraccounts')),
            ],
        ),
    ]
